<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <AssemblyName>Mamby.DotNet</AssemblyName>
    <RootNamespace>Mamby.DotNet</RootNamespace>
    <PackageId>Mamby.DotNet</PackageId>
    <Description>Opinionated .NET utilities.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
