<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <AssemblyName>Mamby.AspNet</AssemblyName>
    <RootNamespace>Mamby.AspNet</RootNamespace>
    <PackageId>Mamby.AspNet</PackageId>
    <Description>Opinionated ASP.NET utilities.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dotnet\Mamby.DotNet.csproj" />
  </ItemGroup>
</Project>
